# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sDvEOtZLEOBz3ybfzXdYf5WKh9CwDubj
"""

from google.colab.patches import cv2_imshow
import cv2
def mashina(rusmi):
  if rusmi=="trcer":
    rasm=cv2.imread("trcer.png")
    cv2_imshow(rasm)
    return "narxi: 203.286.880 so'm"
  elif rusmi=="malibu":
    rasm=cv2.imread("malibu.jpg")
    cv2_imshow(rasm)
    return "narxi: 419.000.960 so'm"
  elif rusmi=="jentra":
    rasm=cv2.imread("jentra.jpg")
    cv2_imshow(rasm)
    return"narxi: 216.827.000 so'm"
  elif rusmi=="kaptiva":
    rasm=cv2.imread("kaptiva.jpg")
    cv2_imshow(rasm)
    return"narxi: 160.580.414 so'm"
  elif rusmi=="jetour":
    rasm=cv2.imread("jetour.jpg")
    cv2_imshow(rasm)
    return"narxi: 287.580.441 so'm"
  elif rusmi=="spark":
    rasm=cv2.imread("spark.jpg")
    cv2_imshow(rasm)
    return"narxi: 100.348.560 so'm"
  elif rusmi=="coblt":
    rasm=cv2.imraed("coblt.jpg")
    cv2_imshow(rasm)
    return"narxi: 146.455.000 so'm"
  else:
    return"Avtomabillar haqida ma'lumot kerak bo'lsa bizga murojat qiling"
rusmi=input("Avtomabil rusmini kirting:")
natija=mashina(rusmi)
print(natija)